//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHIContactInformation.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblContactInformation
    {
        public int ContactID { get; set; }

        [Required(ErrorMessage ="Enter First Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Enter Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Enter Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "Enter Status")]
        public string Status { get; set; }

        [Required(ErrorMessage = "Enter Phone Number")]
        [MinLength(10, ErrorMessage ="Phone Number should be 10 digit")]
        public string PhoneNumber { get; set; }
    }
}
